apiVersion: v2
name: istio-chart
version: 0.0.1
description: Helm chart for deploying Istio cluster
appVersion: 1.16.7
dependencies:
  - name: base
    version: 1.16.7
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.16.7
    repository: https://istio-release.storage.googleapis.com/charts
  # - name: gateway
  #   version: 1.16.7
  #   repository: https://istio-release.storage.googleapis.com/charts
